/**
 * RootLayout.tsx
 * -------------------
 * This is the root layout component for a Next.js 13+ app using the App Router.
 * It sets up global styles, fonts, and metadata for the entire application.
 *
 * Key Features:
 * 1. Imports Google Fonts:
 *    - Geist (sans-serif) and Geist Mono (monospace) with Latin subset.
 *    - Sets CSS variables (--font-geist-sans, --font-geist-mono) for use in styles.
 *
 * 2. Exports Metadata:
 *    - `title`: Page title
 *    - `description`: Page description for SEO and social previews
 *
 * 3. RootLayout Component:
 *    - Wraps all pages in <html> and <body> tags.
 *    - Applies imported font variables and antialiasing via className.
 *    - Accepts `children` (all nested page components) and renders them inside <body>.
 *
 * Usage:
 * This layout will automatically be applied to all pages in the Next.js app
 * if placed in the `app` directory as `layout.tsx`.
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
